import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
    fr: {
        translation: {
            nav: {
                dashboard: 'Tableau de bord',
                members: 'Membres',
                groups: 'Groupes',
                timetable: 'Emploi du temps',
                reports: 'Rapports',
                my_groups: 'Mes Groupes',
                logout: 'Déconnexion',
                filieres_nav: 'Filières',
                salles_nav: 'Salles',
                portal: 'PORTAIL ISTA',
                digital_campus: 'Digital Campus'
            },
            header: {
                admin_access: 'Accès Administrateur',
                formateur_access: 'Accès Formateur',
                theme_toggle: 'Changer le thème',
                settings: 'Paramètres',
                notifications: 'Notifications'
            },
            login: {
                portal_title: 'PORTAIL ISTA',
                attendance_system: 'Système de Gestion des Présences',
                email_address: 'Adresse Email',
                password: 'Mot de passe',
                login_button: 'Se connecter',
                secure_connection: 'Connexion sécurisée ISTA',
                invalid_credentials: 'Identifiants invalides'
            },
            dashboard: {
                hub_name: 'ISTA DIGITAL HUB',
                overview_title: "Vue d'ensemble",
                overview_subtitle: 'Statistiques et Analyse des Présences',
                sync_button: 'Synchronisation',
                total_students: 'Total Stagiaires',
                total_formateurs: 'Formateurs',
                total_groups: 'Groupes Actifs',
                total_reports: 'Rapports Générés',
                status_active: 'ACTIF',
                status_online: 'EN LIGNE',
                status_open: 'OUVERT',
                status_archived: 'ARCHIVÉ',
                attendance_evolution: 'Évolution de la Présence',
                weekly_rate: 'Taux hebdomadaire global',
                current_week: 'Semaine en cours',
                distribution_title: 'Répartition par État',
                attendance_rate: 'PRÉSENCES',
                present: 'PRÉSENT',
                absent: 'ABSENT',
                generate_global_report: 'Générer Rapport Global'
            },
            accounts: {
                title: 'Comptes',
                subtitle: 'Gestion des Membres ISTA',
                all_streams: 'TOUTES LES FILIÈRES',
                add_member: 'AJOUTER UN MEMBRE',
                stream_label: 'Filière',
                search_placeholder: 'RECHERCHER UN STAGIAIRE (NOM, ID, EMAIL)...',
                total_students: 'TOTAL STAGIAIRES',
                student_id: 'ID',
                student_name: 'NOM',
                student_email: 'EMAIL',
                actions: 'ACTIONS',
                select_group_prompt: 'SÉLECTIONNER UN GROUPE POUR VOIR LES MEMBRES',
                no_students: 'AUCUN STAGIAIRE DANS CE GROUPE',
                formateurs_title: 'CORPS ENSEIGNANT',
                formateurs_subtitle: 'LISTE DES FORMATEURS ET INTERVENANTS',
                reset_password_warning: 'AVERTISSEMENT : LA MODIFICATION DU NOM RÉINITIALISERA ÉGALEMENT LE MOT DE PASSE.',
                delete_success: 'Membre supprimé du système.',
                update_success: 'Informations mises à jour.',
                create_success: 'Compte créé avec succès.'
            },
            groups: {
                title: 'Groupes',
                subtitle: 'Filières et Divisions ISTA',
                create_button: 'CRÉER UN GROUPE',
                students_count: 'Stagiaires',
                formateurs: 'Formateur(s)',
                update_title: 'Mise à jour du Groupe',
                group_title_label: 'Titre du Groupe',
                stream_label: 'Filière',
                formateurs_label: 'Formateurs',
                save_button: 'ENREGISTRER',
                init_title: 'Initialiser un Groupe',
                init_subtitle: 'Ajouter une nouvelle division',
                delete_confirm_title: 'Suppression du Groupe',
                delete_confirm_msg: 'Êtes-vous sûr de vouloir supprimer le groupe {{id}}? Cette action supprimera également toutes les séances associées dans l\'emploi du temps.',
                search_placeholder: 'RECHERCHER UN GROUPE...',
                list_title: 'LISTE DES GROUPES D\'ÉTUDES',
                effectif: 'EFFECTIF',
                formateur: 'FORMATEUR',
                no_groups: 'PAS DE GROUPES DISPONIBLES',
                sidebar_overview: 'APERÇU DES SECTIONS',
                active_streams: 'FILIÈRES ACTIVES',
                recent_activities: 'DERNIÈRES ACTIVITÉS',
                update_success: 'Groupe mis à jour avec succès.',
                create_success: 'Groupe créé avec succès.',
                delete_success: 'Groupe supprimé avec succès.'
            },
            timetable: {
                title: 'Emploi du Temps',
                subtitle: 'Gestion administrative du planning',
                add_seance: 'AJOUTER UNE SÉANCE',
                initializing: 'INITIALISATION DU PLANNING...',
                days_header: 'JOURS',
                free_slot: 'LIBRE / VIDE',
                days: {
                    monday: 'LUNDI',
                    tuesday: 'MARDI',
                    wednesday: 'MERCREDI',
                    thursday: 'JEUDI',
                    friday: 'VENDREDI',
                    saturday: 'SAMEDI'
                },
                update_success: 'Séance mise à jour avec succès.',
                create_success: 'Nouvelle séance ajoutée au planning.',
                delete_success: 'Séance supprimée avec succès.',
                list_title: 'PLANIFICATION HEBDOMADAIRE',
                col_session: 'SÉANCE / GROUPE',
                col_time: 'HORAIRES',
                col_formateur: 'FORMATEUR',
                col_actions: 'ACTIONS',
                qualified_formateur: 'FORMATEUR QUALIFIÉ',
                no_sessions: 'PAS DE SÉANCES PROGRAMMÉES',
                delete_confirm_title: 'SUPPRESSION DE SÉANCE',
                delete_confirm_message: 'Êtes-vous sûr de vouloir supprimer cette séance de l\'emploi du temps ?',
                add_session: 'AJOUTER UNE SÉANCE',
                group_select: 'GROUPE',
                formateur_select: 'FORMATEUR',
                day_select: 'JOUR',
                start_time: 'DÉBUT',
                end_time: 'FIN',
                room_label: 'SALLE',
                add_button: 'AJOUTER AU PLANNING',
                select_group_placeholder: 'SÉLECTIONNER UN GROUPE',
                select_formateur_placeholder: 'SÉLECTIONNER UN FORMATEUR',
                room_placeholder: 'EX: SALLE 101'
            },
            reports: {
                title: 'Rapports',
                subtitle: 'Gérez et exportez vos rapports de présence.',
                all_groups: 'TOUS LES GROUPES',
                export_button: 'EXPORTER PDF',
                list_title: 'DOSSIERS DE SÉANCES',
                search: 'RECHERCHER...',
                filter_date: 'FILTRER PAR DATE',
                loading: 'Chargement des rapports...',
                not_found: 'Aucun rapport trouvé pour cette période.',
                adjust_filters: 'Essayez d\'ajuster vos filtres.',
                col_code: 'CODE',
                col_group: 'GROUPE',
                col_module: 'MODULE',
                col_formateur: 'FORMATEUR',
                col_date: 'DATE',
                col_status: 'STATUT',
                col_actions: 'ACTIONS',
                export_republic: 'ROYAUME DU MAROC',
                export_title: 'FEUILLE D\'APPEL JOURNALIÈRE',
                export_presence: 'PRÉSENCE',
                export_code: 'Réf. Rapport',
                export_module: 'Module',
                export_formateur: 'Formateur',
                export_stats: 'Statistiques',
                export_student: 'Nom du Stagiaire',
                export_id: 'Matricule',
                export_status: 'Signature/Statut',
                export_footer: 'Document généré par le Système Digital de Pointage OFPPT'
            },
            scanner: {
                digital_tag: 'Système de Pointage Digital',
                title: 'Scanner de Présence',
                exit_tooltip: 'Fermer',
                finish_button: 'TERMINER',
                validating: 'VALIDATION...',
                group_label: 'GROUPE',
                session_label: 'SÉANCE',
                attendance_label: 'PRÉSENCES',
                offline: 'Scanner Hors Ligne',
                active_message: 'SCANNER OPTIQUE ACTIF',
                description: 'SYSTÈME DE RECONNAISSANCE QR-CODE & BIOMÉTRIQUE EN COURS SUR LE SERVEUR',
                already_scanned: 'DÉJÀ POINTÉ',
                error_label: 'ERREUR',
                server_status: 'Serveur ISTA Connecté',
                interface_tag: 'Interface Responsive',
                campus: 'ISTA MIRLEFT CAMPUS',
                automated: 'ISTA DIGITAL SYSTEM — SESSION AUTOMATISÉE',
                success_msg: 'Scannage terminé avec succès. Les présences ont été archivées.',
                save_error: 'Échec de l\'enregistrement. Veuillez réessayer.'
            },
            modals: {
                identity: {
                    editing: 'ÉDITION',
                    new: 'NOUVELLE',
                    label: 'IDENTITÉ',
                    service_tag: 'Service de Gestion des Comptes',
                    system_id: 'ID SYSTÈME',
                    auto_gen: 'GÉNÉRATION AUTO',
                    group_label: 'GROUPE ACTUEL',
                    global_access: 'ACCÈS GLOBAL',
                    updating: 'MISE À JOUR',
                    init: 'INITIALISATION',
                    title: 'Détails du membre',
                    subtitle: 'Veuillez renseigner les paramètres d\'accès ci-dessous.',
                    full_name: 'Nom Complet',
                    access_level: 'Niveau d\'Accès',
                    group_assignment: 'Affectation aux Groupes',
                    no_req: 'Accès global au système - Aucun groupe requis',
                    select_group: 'SÉLECTIONNER UN GROUPE...',
                    select_groups: 'SÉLECTIONNER LES GROUPES...',
                    save: 'Enregistrer les modifications',
                    create: 'Créer le profil membre',
                    name_placeholder: 'Prénom et Nom...'
                },
                roles: {
                    stagiaire: 'Stagiaire',
                    formateur: 'Formateur',
                    admin: 'Administrateur'
                },
                dossier: {
                    title: 'Rapport de Présence',
                    subtitle: 'Définissez les détails du cours pour l\'emploi du temps.',
                    unit_label: 'UNITÉ OPÉRATIONNELLE',
                    signature_label: 'Signature du Formateur',
                    sign_here: 'Émargez ici',
                    clear: 'Effacer',
                    seance_header: 'SÉANCE',
                    submit: 'FINALISER ET TRANSMETTRE LE RAPPORT',
                    validating: 'VALIDATION OPÉRATIONNELLE...',
                    sig_req: 'La signature du formateur est requise pour valider le rapport.',
                    enrolled: 'ENROLÉS',
                    list_title: 'Liste des Stagiaires'
                },
                group: {
                    code: 'CODE DU GROUPE',
                    stream: 'FILIÈRE / STREAM',
                    name: 'NOM DU GROUPE / TITRE',
                    formateurs: 'FORMATEURS RÉFÉRENTS',
                    select_formateurs: 'Sélectionner les formateurs...',
                    create: 'Créer le Groupe'
                },
                confirm: {
                    cancel: 'ANNULER',
                    confirm: 'CONFIRMER',
                    critical: 'ACTION CRITIQUE'
                }
            },
            common: {
                verified: 'VÉRIFIÉ',
                last_login: 'Dernière Connexion',
                matricule: 'MATRICULE',
                no_data: 'Aucune donnée trouvée pour ce groupe.',
                loading: 'Chargement...',
                cancel: 'ANNULER',
                confirm: 'CONFIRMER'
            },
            formateur: {
                initializing: 'INITIALISATION DU TERMINAL...',
                welcome: 'BIENVENU, {{name}}',
                session: 'SESSION {{group}}',
                select_prompt: 'SÉLECTIONNEZ UN GROUPE POUR COMMENCER',
                select_group: 'CHOISIR UN GROUPE',
                validate_attendance: 'VALIDER LA PRÉSENCE',
                scanner_tooltip: 'OUVRIR LE SCANNER',
                enrolled_students: 'STAGIAIRES INSCRITS',
                list_title: 'LISTE DE VÉRIFICATION',
                search_placeholder: 'RECHERCHER UN STAGIAIRE...',
                manual_actions: 'ACTIONS MANUELLES',
                no_students: 'AUCUN STAGIAIRE TROUVÉ DANS CE GROUPE',
                waiting_session: 'EN ATTENTE DE SÉLECTION...',
                update_fail: 'ÉCHEC DE LA MISE À JOUR MANUELLE',
                report_success: 'RAPPORT DE {{group}} TRANSMIS AVEC SUCCÈS',
                report_error: 'ERREUR LORS DE LA TRANSMISSION'
            },
            divisions: {
                title: 'Groupes',
                subtitle: 'Registre des Groupes Supervisés',
                search_placeholder: 'RECHERCHER UN STAGIAIRE...',
                state: 'État',
                selected: 'GROUPE SÉLECTIONNÉ',
                waiting: 'EN ATTENTE',
                manifest: 'Manifeste',
                last_login_data: 'Donnée indisponible',
                loading: 'Chargement du Registre...',
                error_fetch: 'Échec de la récupération des groupes.'
            },
            formateur_timetable: {
                title: 'Emploi du Temps',
                subtitle: 'VOTRE EMPLOI DU TEMPS PERSONNEL',
                no_assignment: 'AUCUNE AFFECTATION',
                no_assignment_msg: 'VOUS N\'AVEZ PAS ENCORE DE GROUPES AFFECTÉS.',
                active_session: 'PROCHAINEMENT',
                loading: 'SYNCHRONISATION DU PLANNING...',
                error_fetch: 'ERREUR LORS DE LA RÉCUPÉRATION DU PLANNING'
            },
            datepicker: {
                months: ["JANVIER", "FÉVRIER", "MARS", "AVRIL", "MAI", "JUIN", "JUILLET", "AOÛT", "SEPTEMBRE", "OCTOBRE", "NOVEMBRE", "DÉCEMBRE"],
                days: ["DIM", "LUN", "MAR", "MER", "JEU", "VEN", "SAM"],
                clear: 'EFFACER LA SÉLECTION',
                placeholder: 'CHOISIR UNE DATE...'
            }
        }
    },
    ar: {
        translation: {
            nav: {
                dashboard: 'لوحة القيادة',
                members: 'الأعضاء',
                groups: 'المجموعات',
                timetable: 'الجدول الزمني',
                reports: 'التقارير',
                my_groups: 'مجموعاتي',
                logout: 'تسجيل الخروج',
                filieres_nav: 'الشعب',
                salles_nav: 'القاعات',
                portal: 'بوابة ISTA',
                digital_campus: 'الحرم الرقمي'
            },
            header: {
                admin_access: 'دخول المسؤول',
                formateur_access: 'دخول المكون',
                theme_toggle: 'تغيير المظهر',
                settings: 'الإعدادات',
                notifications: 'التنبيهات'
            },
            login: {
                portal_title: 'بوابة ISTA',
                attendance_system: 'نظام إدارة الحضور',
                email_address: 'البريد الإلكتروني',
                password: 'كلمة المرور',
                login_button: 'تسجيل الدخول',
                secure_connection: 'اتصال آمن ISTA',
                invalid_credentials: 'بيانات الاعتماد غير صالحة'
            },
            dashboard: {
                hub_name: 'مركز ISTA الرقمي',
                overview_title: 'نظرة عامة',
                overview_subtitle: 'إحصائيات وتحليل الحضور',
                sync_button: 'مزامنة',
                total_students: 'إجمالي المتدربين',
                total_formateurs: 'المكونون',
                total_groups: 'المجموعات النشطة',
                total_reports: 'التقارير التي تم إنشاؤها',
                status_active: 'نشط',
                status_online: 'متصل',
                status_open: 'مفتوح',
                status_archived: 'مؤرشف',
                attendance_evolution: 'تطور الحضور',
                weekly_rate: 'المعدل الأسبوعي الإجمالي',
                current_week: 'الأسبوع الحالي',
                distribution_title: 'التوزيع حسب الحالة',
                attendance_rate: 'الحضور',
                present: 'حاضر',
                absent: 'غائب',
                generate_global_report: 'إنشاء تقرير عام'
            },
            accounts: {
                title: 'الحسابات',
                subtitle: 'إدارة أعضاء ISTA',
                all_streams: 'جميع الشعب',
                add_member: 'إضافة عضو',
                stream_label: 'الشعبة',
                search_placeholder: 'البحث عن متدرب (الاسم، المعرف، البريد الإلكتروني)...',
                total_students: 'المتدربون المسجلون',
                student_id: 'المعرف',
                student_name: 'الاسم',
                student_email: 'البريد الإلكتروني',
                actions: 'عمليات',
                select_group_prompt: 'اختر مجموعة لعرض الأعضاء',
                no_students: 'لا يوجد متدربين في هذه المجموعة',
                formateurs_title: 'هيئة التدريس',
                formateurs_subtitle: 'قائمة المكونين والمتدخلين',
                reset_password_warning: 'إذا قمت بتغيير الاسم، فسيتم إعادة تعيين كلمة المرور افتراضيًا (12345678).',
                delete_success: 'تم حذف المستخدم بنجاح',
                update_success: 'تم تحديث المستخدم بنجاح',
                create_success: 'تم إنشاء المستخدم بنجاح',
                list_title: 'قائمة الأعضاء النشطين',
                portal_link: 'مرتبط ببوابة DAD',
                delete_confirm_title: 'حذف الحساب',
                delete_confirm_message: 'هل أنت متأكد من رغبتك في حذف هذا العضو من النظام نهائيًا؟'
            },
            groups: {
                title: 'المجموعات',
                subtitle: 'شعب وأقسام ISTA',
                create_button: 'إنشاء مجموعة',
                students_count: 'المتدربون',
                formateurs: 'المكون(ون)',
                update_title: 'تحديث المجموعة',
                group_title_label: 'عنوان المجموعة',
                stream_label: 'الشعبة',
                formateurs_label: 'المكونون',
                save_button: 'حفظ',
                init_title: 'بدء مجموعة',
                init_subtitle: 'إضافة قسم جديد',
                delete_confirm_title: 'حذف المجموعة',
                delete_confirm_msg: 'هل أنت متأكد أنك تريد حذف المجموعة {{id}}؟ سيؤدي هذا الإجراء أيضًا إلى حذف جميع الحصص المرتبطة في الجدول الزمني.',
                search_placeholder: 'البحث عن مجموعة...',
                list_title: 'قائمة المجموعات الدراسية',
                effectif: 'العدد',
                formateur: 'المكون',
                no_groups: 'لا توجد مجموعات متاحة',
                sidebar_overview: 'نظرة عامة على الأقسام',
                active_streams: 'الشعب النشطة',
                recent_activities: 'الأنشطة الأخيرة',
                update_success: 'تم تحديث المجموعة بنجاح.',
                create_success: 'تم إنشاء المجموعة بنجاح.',
                delete_success: 'تم حذف المجموعة بنجاح.'
            },
            timetable: {
                title: 'الجدول الزمني',
                subtitle: 'الإدارة الإدارية للتخطيط',
                add_seance: 'إضافة حصة',
                initializing: 'تهيئة الجدول الزمني...',
                days_header: 'الأيام',
                free_slot: 'فارغ',
                days: {
                    monday: 'الاثنين',
                    tuesday: 'الثلاثاء',
                    wednesday: 'الأربعاء',
                    thursday: 'الخميس',
                    friday: 'الجمعة',
                    saturday: 'السبت'
                },
                update_success: 'تم تحديث الحصة بنجاح.',
                create_success: 'تمت إضافة حصة جديدة إلى الجدول.',
                delete_success: 'تم حذف الحصة بنجاح.',
                list_title: 'التخطيط الأسبوعي',
                col_session: 'الحصة / المجموعة',
                col_time: 'المواعيد',
                col_formateur: 'المكون',
                col_actions: 'عمليات',
                qualified_formateur: 'مكون مؤهل',
                no_sessions: 'لا توجد حصص مبرمجة',
                delete_confirm_title: 'حذف الحصة',
                delete_confirm_message: 'هل أنت متأكد من رغبتك في حذف هذه الحصة من الجدول الزمني؟',
                add_session: 'إضافة حصة',
                group_select: 'المجموعة',
                formateur_select: 'المكون',
                day_select: 'اليوم',
                seance_header: 'الحصة',
                room_label: 'القاعة',
                add_button: 'إضافة إلى الجدول',
                select_group_placeholder: 'اختر مجموعة',
                select_formateur_placeholder: 'اختر مكوناً',
                room_placeholder: 'مثال: القاعة 101'
            },
            reports: {
                title: 'التقارير',
                subtitle: 'إدارة وتصدير تقارير الحضور الخاصة بك.',
                all_groups: 'جميع المجموعات',
                export_button: 'تصدير PDF',
                list_title: 'ملفات الحصص',
                search: 'بحث...',
                filter_date: 'تصفية حسب التاريخ',
                loading: 'جاري تحميل التقارير...',
                not_found: 'لم يتم العثور على تقارير لهذه الفترة.',
                adjust_filters: 'حاول تعديل الفلاتر الخاصة بك.',
                col_code: 'الرمز',
                col_group: 'المجموعة',
                col_module: 'الوحدة',
                col_formateur: 'المكون',
                col_date: 'التاريخ',
                col_status: 'الحالة',
                col_actions: 'عمليات',
                export_republic: 'المملكة المغربية',
                export_title: 'ورقة الحضور اليومية',
                export_presence: 'الحضور',
                export_code: 'مرجع التقرير',
                export_module: 'الوحدة',
                export_formateur: 'المكون',
                export_stats: 'إحصائيات',
                export_student: 'اسم المتدرب',
                export_id: 'رقم التسجيل',
                export_status: 'التوقيع/الحالة',
                export_footer: 'تم إنشاء هذا المستند بواسطة نظام التنقيط الرقمي لـ OFPPT'
            },
            scanner: {
                digital_tag: 'نظام التنقيط الرقمي',
                title: 'ماسح الحضور',
                exit_tooltip: 'إغلاق',
                finish_button: 'إنهاء',
                validating: 'جاري التحقق...',
                group_label: 'المجموعة',
                session_label: 'الحصة',
                attendance_label: 'الحضور',
                offline: 'الماسح غير متصل',
                active_message: 'الماسح الضوئي نشط',
                description: 'نظام التعرف على رمز QR والقياسات الحيوية قيد التنفيذ على الخادم',
                already_scanned: 'تم التسجيل مسبقاً',
                error_label: 'خطأ',
                server_status: 'خادم ISTA متصل',
                interface_tag: 'واجهة متجاوبة',
                campus: 'حرم ISTA ميرلفت',
                automated: 'نظام ISTA الرقمي - حصة مؤتمتة',
                success_msg: 'تم الانتهاء من المسح بنجاح. تم أرشفة الحضور.',
                save_error: 'فشل التسجيل. يرجى المحاولة مرة أخرى.'
            },
            modals: {
                identity: {
                    editing: 'تعديل',
                    new: 'جديد',
                    label: 'الهوية',
                    service_tag: 'خدمة إدارة الحسابات',
                    system_id: 'معرف النظام',
                    auto_gen: 'توليد تلقائي',
                    group_label: 'المجموعة الحالية',
                    global_access: 'وصول عام',
                    updating: 'تحديث',
                    init: 'بدء',
                    title: 'تفاصيل العضو',
                    subtitle: 'يرجى ملء معلمات الوصول أدناه.',
                    full_name: 'الاسم الكامل',
                    access_level: 'مستوى الوصول',
                    group_assignment: 'التعيين في المجموعات',
                    no_req: 'وصول عام للنظام - لا توجد مجموعة مطلوبة',
                    select_group: 'اختر مجموعة...',
                    select_groups: 'اختر المجموعات...',
                    save: 'حفظ التعديلات',
                    create: 'إنشاء ملف تعريف العضو',
                    name_placeholder: 'الاسم والنسب...'
                },
                roles: {
                    stagiaire: 'متدرب',
                    formateur: 'مكون',
                    admin: 'مسؤول'
                },
                dossier: {
                    title: 'تقرير الحضور',
                    subtitle: 'حدد تفاصيل الحصة للجدول الزمني.',
                    unit_label: 'الوحدة التشغيلية',
                    signature_label: 'توقيع المكون',
                    sign_here: 'وقع هنا',
                    clear: 'مسح',
                    seance_header: 'الحصة',
                    submit: 'إنهاء وإرسال التقرير',
                    validating: 'جاري التحقق التشغيلي...',
                    sig_req: 'توقيع المكون مطلوب للمصادقة على التقرير.',
                    enrolled: 'مسجلين',
                    list_title: 'قائمة المتدربين'
                },
                group: {
                    code: 'رمز المجموعة',
                    stream: 'الشعبة',
                    name: 'اسم المجموعة / العنوان',
                    formateurs: 'المكونون المرجعيون',
                    select_formateurs: 'اختر المكونين...',
                    create: 'إنشاء المجموعة'
                },
                confirm: {
                    cancel: 'إلغاء',
                    confirm: 'تأكيد',
                    critical: 'إجراء حرج'
                }
            },
            common: {
                verified: 'تم التحقق',
                last_login: 'آخر تسجيل دخول',
                matricule: 'رقم التسجيل',
                no_data: 'لم يتم العثور على بيانات لهذه المجموعة.',
                loading: 'جاري التحميل...',
                cancel: 'إلغاء',
                confirm: 'تأكيد'
            },
            formateur: {
                welcome: 'مرحباً، السيد {{name}}',
                session: 'الحصة : {{group}}',
                select_prompt: 'يرجى اختيار مجموعة لبدء الحصة.',
                select_group: 'اختر مجموعة',
                validate_attendance: 'تصديق الحضور',
                scanner_tooltip: 'تشغيل الماسح الضوئي',
                enrolled_students: 'المتدربون المسجلون',
                list_title: 'قائمة المتدربين',
                search_placeholder: 'البحث بالاسم...',
                no_students: 'لم يتم العثور على متدربين في هذه المجموعة.',
                waiting_session: 'في انتظار بدء الحصة',
                manual_actions: 'عمليات يدوية',
                initializing: 'جاري تهيئة البوابة...',
                update_fail: 'فشل التحديث اليدوي.',
                report_success: 'تم أرشفة تقرير المجموعة {{group}}.',
                report_error: 'خطأ أثناء الإرسال.'
            },
            divisions: {
                title: 'المجموعات',
                subtitle: 'سجل المجموعات المشرف عليها',
                search_placeholder: 'البحث عن متدرب...',
                state: 'الحالة',
                selected: 'المجموعة المختارة',
                waiting: 'في الانتظار',
                manifest: 'البيان',
                last_login_data: 'البيانات غير متوفرة',
                loading: 'جاري تحميل السجل...',
                error_fetch: 'فشل استرجاع المجموعات.'
            },
            formateur_timetable: {
                title: 'الجدول الزمني',
                subtitle: 'جدول النشر الشخصي الخاص بي',
                no_assignment: 'لا يوجد تكليف نشط',
                no_assignment_msg: 'أنت غير معين حالياً لأي مجموعة عملياتية.',
                active_session: 'حصة نشطة',
                loading: 'جاري تحميل الجدول...',
                error_fetch: 'فشل استرجاع الجدول الزمني الشخصي.'
            },
            datepicker: {
                months: ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"],
                days: ["أحد", "اثنين", "ثلاثاء", "أربعاء", "خميس", "جمعة", "سبت"],
                clear: 'مسح التحديد',
                placeholder: 'اختر تاريخاً...'
            }
        }
    }
};

i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        resources,
        fallbackLng: 'fr',
        interpolation: {
            escapeValue: false
        }
    });

export default i18n;
